#!/usr/bin/env node
/**
 * Vendors the FULL World English Bible (WEB) into src/data/scripture.ts.
 *
 * Source: getbible.net "web" translation (66 books, one request each).
 * Run once:  node scripts/fetch-bible.mjs
 * Regenerates the complete offline Bible used across the app.
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const BASE = "https://api.getbible.net/v2/web";
const BOOKS = 66; // the whole Bible
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const verses = new Map(); // "Genesis 1:1" -> text
const chapters = new Map(); // "Genesis 1" -> [{n,text}]

let failures = [];
for (let n = 1; n <= BOOKS; n++) {
  let ok = false;
  for (let attempt = 0; attempt < 6 && !ok; attempt++) {
    try {
      const res = await fetch(`${BASE}/${n}.json`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const book = await res.json();
      if (!book.chapters?.length) throw new Error("no chapters");
      for (const ch of book.chapters) {
        const ck = `${book.name} ${ch.chapter}`;
        if (!chapters.has(ck)) chapters.set(ck, []);
        for (const v of ch.verses) {
          const text = v.text.replace(/\s+/g, " ").trim();
          verses.set(`${book.name} ${v.chapter}:${v.verse}`, text);
          chapters.get(ck).push({ n: v.verse, text });
        }
      }
      ok = true;
    } catch (err) {
      if (attempt === 5) failures.push(`${n} — ${err.message}`);
      else await sleep(1500 * (attempt + 1));
    }
  }
  if (n % 10 === 0) process.stdout.write(`fetched ${n}/${BOOKS}\n`);
}

if (failures.length) {
  console.error("FAILURES:", failures);
  process.exit(1);
}

// ---- sanity checks ----------------------------------------------------------
const chapterCount = chapters.size;
console.log(`\nDownloaded ${BOOKS} books:`);
console.log(`  chapters: ${chapterCount} (WEB has 1189)`);
console.log(`  verses:   ${verses.size} (WEB has ~31,102)`);

if (chapterCount !== 1189) {
  console.error("Chapter count mismatch — aborting.");
  process.exit(1);
}

// ---- make sure every reference already used in the app still resolves ------
function sourcePaths() {
  const paths = [];
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.name.startsWith(".")) continue;
      const p = resolve(dir, entry.name);
      if (entry.isDirectory()) walk(p);
      else if (/\.(ts|tsx)$/.test(entry.name)) paths.push(p);
    }
  };
  walk(resolve(root, "src"));
  return paths;
}
const BOOK_NAMES = new Set([
  "Genesis","Exodus","Leviticus","Numbers","Deuteronomy","Joshua","Judges","Ruth",
  "1 Samuel","2 Samuel","1 Kings","2 Kings","1 Chronicles","2 Chronicles","Ezra",
  "Nehemiah","Esther","Job","Psalms","Proverbs","Ecclesiastes","Song of Solomon",
  "Isaiah","Jeremiah","Lamentations","Ezekiel","Daniel","Hosea","Joel","Amos",
  "Obadiah","Jonah","Micah","Nahum","Habakkuk","Zephaniah","Haggai","Zechariah",
  "Malachi","Matthew","Mark","Luke","John","Acts","Romans","1 Corinthians",
  "2 Corinthians","Galatians","Ephesians","Philippians","Colossians",
  "1 Thessalonians","2 Thessalonians","1 Timothy","2 Timothy","Titus","Philemon",
  "Hebrews","James","1 Peter","2 Peter","1 John","2 John","3 John","Jude","Revelation",
]);
const source = sourcePaths().map((p) => readFileSync(p, "utf8")).join("\n");
const missing = new Set();
for (const m of source.matchAll(/\b(?:\d\s)?[A-Za-z]+(?:\s[A-Za-z]+)*\s\d+:\d+(?:-\d+)?\b/g)) {
  const raw = m[0];
  const [name, range] = raw.split(/\s(\d+:\d+(?:-\d+)?)$/).filter(Boolean);
  if (!BOOK_NAMES.has(name)) continue;
  const [, c, vFrom, vTo] = range.match(/^(\d+):(\d+)(?:-(\d+))?$/);
  for (let v = +vFrom; v <= (+vTo ?? +vFrom); v++) {
    if (!verses.has(`${name} ${c}:${v}`)) missing.add(`${name} ${c}:${v}`);
  }
}
if (missing.size) {
  console.error("MISSING referenced verses:", [...missing].slice(0, 20));
  process.exit(1);
}

// ---- write ------------------------------------------------------------------
const verseLines = [...verses.keys()]
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))
  .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(verses.get(k))},`);

const chapterLines = [...chapters.keys()]
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))
  .map((k) => {
    const rows = chapters
      .get(k)
      .map((v) => `    { n: ${v.n}, text: ${JSON.stringify(v.text)} }`)
      .join(",\n");
    return `  ${JSON.stringify(k)}: [\n${rows},\n  ],`;
  });

const header = `// GENERATED by scripts/fetch-bible.mjs — do not edit by hand.
// The complete World English Bible (public domain), vendored for offline use.
// Source: getbible.net (translation "web").

export const translation = "World English Bible";
export const translationNote = "Public Domain";

`;

const versesBlock = `export const verses: Record<string, string> = {\n${verseLines.join("\n")}\n};\n`;
const chaptersBlock = `\nexport const chapters: Record<string, { n: number; text: string }[]> = {\n${chapterLines.join("\n")}\n};\n`;

writeFileSync(resolve(root, "src/data/scripture.ts"), header + versesBlock + chaptersBlock);
console.log(`\nWrote src/data/scripture.ts  (${((versesBlock.length + chaptersBlock.length) / 1024).toFixed(1)} KB of data)`);
